services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: saas-skeleton-app
    container_name: saas-skeleton-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - PHP_EXTENSION_INSTALL=zip,gd
    networks:
      - app-network
    depends_on:
      - db
      - redis

  webserver:
    image: nginx:alpine
    container_name: saas-skeleton-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: saas-skeleton-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: saas_skeleton
      MYSQL_USER: saas_user
      MYSQL_PASSWORD: saas_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: saas-skeleton-redis
    restart: unless-stopped
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
